name: "Newman Tests"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setUp:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - uses: actions/checkout@v1
      
      - name: Build environment
        run: |
          newman --version
          npm install -g newman-reporter-htmlextra  

      - name: Run Postman collection
        run: |
            newman run ./collection/SpaceX.postman_collection.json -e ./environment/SpaceX.postman_environment.json -r htmlextra,cli,allure --reporter-htmlextra-export ./testResults/htmlreport.html
      
      - name: Download a Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
            name: report-spacex.html
            path: testResults

      - name: Allure report
        if: always()
        # You may pin to the exact commit or the version.
        # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
        uses: afiore/action-allure-report@v0.1.0
        with:
          # Allure test result data dir
          results-dir: ./allure-results
          # Allure report target dir
          report-dir: ./allure-report

