name: "Newman Tests"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - uses: actions/checkout@v1
      - name: Run API Tests
        run: newman run ./collection/SpaceX.postman_collection.json -e ./environment/SpaceX.postman_environment.json --reporters cli,htmlextra
